on:
  push:
  pull_request:

jobs:
  build:
    name: tsc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install node v12
        uses: actions/setup-node@v2
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version: 12
      - name: npm install
        run: npm install
      - name: tsc
        run: npm run build
      - name: publish
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}