on:
  push:
  pull_request:

jobs:
  build:
    name: tsc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install node v12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: yarn install
        run: yarn install
      - name: tsc
        uses: icrawl/action-tsc@v1
      - name: setup node
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version: 12
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}